name: dev-image
on:
  push:
    tags:
      - 'v*.*.*'
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Free up disk space"
        uses: ./.github/actions/free-up-disk-space
      - name: Determine image tag
        id: tag
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            TAG="${{ github.event.release.tag_name }}"
          elif [ "${{ github.ref_type }}" = "tag" ]; then
            TAG="${GITHUB_REF_NAME}"
          else
            TAG="dev"
          fi
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
      - name: Build image
        run: |
          docker build \
            -t fms-hf-tuning:${IMAGE_TAG}-nvcr \
            -t fms-hf-tuning:staging-nvcr-latest \
            -f build/nvcr.Dockerfile .
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Push docker image to Quay.io
        run: |
            docker push ${{ env.QUAY_REPOSITORY }}/fms-hf-tuning:staging-nvcr-latest
            docker push ${{ env.QUAY_REPOSITORY }}/fms-hf-tuning:${IMAGE_TAG}-nvcr